version: "3.1"
services:
  plsql:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: hamid318
#
#  adminer:
#    image: adminer
#    restart: unless-stopped
#    ports:
#      - 8080:8080