server:
  port: 8501

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

spring:
  application:
    name: account-service
  cloud:
    cassandra:
      contact:
        point: localhost
      port: 9042
      username: cassandra
      password: cassandra
      keyspace:
        name: springcloud
  zipkin:
    base-url: http://localhost:9411/
  boot:
    admin:
      client:
        url: http://localhost:8508

management:
  endpoints:
    web:
      exposure:
        include: "*"