server:
  port: 8503

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

spring:
  application:
    name: notification-service
  rabbitmq:
    username: testhamid318
    password: testhamid318
  cloud:
    stream:
      bindings:
        input:
          destination: ms-queue
  zipkin:
    base-url: http://localhost:9411/

  boot:
    admin:
      client:
        url: http://localhost:8508

management:
  endpoints:
    web:
      exposure:
        include: "*"