spring:
  application:
    name: zuul-gateway-server
  datasource:
    url: jdbc:mysql://localhost:3306/courseclub?createDatabaseIfNotExist=true&useSSL=true&serverTimezone=Asia/Baku&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hamid318
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
      org.hibernate.envers.audit_table_suffix: _log

server:
  servlet:
    context-path: /api
  port: 8001

zuul:
  routes:
    dummy-service:
      path: /dummy/**
      service-id: dummy-service
    user-service:
      path: /users/**
      service-id: user-service
    auth-service:
      path: /auth/**
      service-id: auth-service
    course-service:
      path: /courses/**
      service-id: course-service
    coupon-service:
      path: /coupons/**
      service-id: coupon-service
  sensitive-headers: null
#  host:
#    connect-timeout-millis: 60000
#    socket-timeout-millis: 60000

ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 1
  client:
    fetch-registry: true
    register-with-eureka: false
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


jwt:
  token:
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDJtPJFD3WKrP4yQvaBVvb4jPnEG0U86NigSl2VR6O6ecFg9QJwlbsZbOCRFFZW14pkK5CdvhkHglU+d+kbMuKUTGULnECSQJ4651HllBRx/rxsBDDjbgD/hF7fZNUPDqxOXiwYlp2kHx+Ra8eahqNr702oMxg5Skve30r2FycsbwIDAQAB
