spring:
  application:
    name: dummy-service

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true

